### ISSUE TITLE
Time to update npm?

### ISSUE THREAD

**Issue by SimonEast** [shkuznetsov/mcopy#1]
Hi there,

Thanks so much for your module. It's one of the few that supports a progress emitter with a custom list of files. I'm using it for a backup script. 😄 👍 

I just noticed that the version on npm is pretty out of date with your repo. Should I use the repo version for the latest improvements? Or could you update npm with your latest changes?

Cheers,
Simon.

**Comment by shkuznetsov** [comment]
Oh wow! You spooked me :) Didn't think anyone's interested in this module.

As you have probably seen I have started a complete overhaul of the code. This is to satisfy the needs of my personal project, which, as hobby projects go, doesn't have any deadline, apart from "somewhere in this life". Don't think I am ready to push it to npm just yet, as I literally just finished working on the "happy path" implementation and tests, so need to invest time into the edgecases and documentation. Think the API won't change much, so it is safe-ish to use it as is, but minor changes may happen if I hit a blocker.

I would be happy to accept any comments and/or contributions, it is always satisfying to help others as well as oneself!

Regards,
Alexander

**Comment by SimonEast** [comment]
OK, sure, thanks for the update. I might try your latest Github version and see how it goes. Did you get around to implementing the `destCreateDir` option? That would be real useful.

One other possible improvement I was looking at was for the copied files to keep the same created and modified dates as the original file (which is pretty important for accurate backups). I think I *might* be able to achieve that post-copy by updating the timestamps from one of the mcopy callbacks, but if you think that might be a useful option to have within your module, I could work that in and submit a pull request.

**Comment by shkuznetsov** [comment]
Yes, creating dirs is now possible with `createDir: true` (which is a default value). Not sure I documented the new opts object yet. Here's some code to give you an idea:
```
const defaults = {
	deleteSource: false,
	createDir: true,
	overwrite: false,
	failOnError: true,
	concurrency: shouldBePositiveIntegerOrDefaultsTo(1),
	highWaterMark: shouldBePositiveIntegerOrDefaultsTo(4194304), // 4M
	globOpt: shouldBeObjectOrDefaultsTo({
		unique: shouldAlwaysBe(true),
		onlyFiles: shouldAlwaysBe(true),
		objectMode: shouldAlwaysBe(true)
	})
};
```
In regards to not changing file attributes — that is actually very valuable, I will need that feature too (I am working on some sort of archiving solution as well, obviously). By all means, send the MR, if you don't mind getting your head around how my convoluted code works.
